<script setup lang="ts">
definePageMeta({middleware:['auth','admin']})
const empty=()=>({en:'',sl:'',de:'',hr:'',sr:''})
const make=()=>({id:null as number|null,title:empty(),content:empty(),active:true,recurring:false,valid_from:'',valid_to:''})
const form=ref(make());const opened=ref(false);const busy=ref(false);const error=ref('')
const {data:news,refresh}=await useFetch<any[]>('/api/admin/news')
function open(item?:any){form.value=make();if(item)Object.assign(form.value,structuredClone(item),{active:!!item.active,recurring:!!item.recurring,valid_from:item.valid_from||'',valid_to:item.valid_to||''});opened.value=true;error.value=''}
async function save(){busy.value=true;error.value='';try{await $fetch(form.value.id?`/api/admin/news/${form.value.id}`:'/api/admin/news',{method:form.value.id?'PATCH':'POST',body:{...form.value,valid_from:form.value.valid_from||null,valid_to:form.value.valid_to||null}});opened.value=false;await refresh()}catch(e:any){error.value=e?.data?.statusMessage||'Napaka pri shranjevanju'}finally{busy.value=false}}
async function toggle(n:any){await $fetch(`/api/admin/news/${n.id}`,{method:'PATCH',body:{active:!n.active}});await refresh()}
async function remove(n:any){if(!confirm('Res izbrisati to novico?'))return;await $fetch(`/api/admin/news/${n.id}`,{method:'DELETE'});await refresh()}
</script>
<template><div><div class="mb-6 flex items-center justify-between"><h1 class="text-xl font-semibold text-stone-800">Novice za goste</h1><button class="rounded-lg bg-pine-600 px-3 py-2 text-sm text-white" @click="open()">+ Nova novica</button></div>
<div class="divide-y divide-stone-100 overflow-hidden rounded-xl border border-stone-200 bg-white"><p v-if="!news?.length" class="p-6 text-center text-sm text-stone-400">Ni novic.</p><div v-for="n in news" :key="n.id" class="flex flex-wrap items-center gap-3 p-4" :class="{'opacity-50':!n.active}"><div class="min-w-0 flex-1"><p class="font-medium text-stone-800">{{n.title.sl||n.title.en}}</p><p v-if="n.valid_from||n.valid_to" class="mt-1 text-xs text-amber-700">{{n.recurring?'Vsako leto · ':''}}{{n.valid_from||'…'}} → {{n.valid_to||'…'}}</p></div><button class="text-xs text-stone-500" @click="toggle(n)">{{n.active?'Skrij':'Prikaži'}}</button><button class="text-xs text-pine-700" @click="open(n)">Uredi</button><button class="text-xs text-red-600" @click="remove(n)">Izbriši</button></div></div>
<Teleport to="body"><div v-if="opened" class="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4" @click.self="opened=false"><form class="max-h-[92vh] w-full max-w-2xl space-y-4 overflow-y-auto rounded-2xl bg-white p-6" @submit.prevent="save"><h2 class="font-semibold">{{form.id?'Uredi novico':'Nova novica'}}</h2><AdminLocalizedInput v-model="form.title" label="Naslov"/><AdminLocalizedInput v-model="form.content" label="Vsebina" multiline :rows="5"/><AdminValidityFields v-model:recurring="form.recurring" v-model:valid-from="form.valid_from" v-model:valid-to="form.valid_to"/><label class="flex items-center gap-2 text-sm"><input v-model="form.active" type="checkbox"/> Aktivna</label><p v-if="error" class="text-sm text-red-600">{{error}}</p><div class="flex gap-3"><button :disabled="busy" class="flex-1 rounded-lg bg-pine-600 py-2 text-sm text-white">{{busy?'Shranjujem…':'Shrani'}}</button><button type="button" class="flex-1 rounded-lg bg-stone-100 py-2 text-sm" @click="opened=false">Prekliči</button></div></form></div></Teleport></div></template>
